name: Puzzles HQ workflow

on:
  release:
    types: [published]

jobs:
  edit-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Edit Version Manifest
        run: cd versioning & python main.py
        env:
          GITHUB_REF: ${{ github.ref }}

#  publish-release:
#    uses: PuzzlesHQ/Puzzles-Workflows/.github/workflows/maven-publishing.yml@main
#    secrets: inherit
#    with:
#      TAG_NAME: ${{ github.event.release.tag_name }}
#