name: Puzzles HQ workflow

on:
  release:
    types: [published]

jobs:
  edit-manifest:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Get Email of release maker
        id: emailGetter
        uses: evvanErb/get-github-email-by-username-action@v2.0
        with:
          github-username: ${{ github.triggering_actor }}
        run: echo "::add-mask::"
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.14'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.14'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Edit Version Manifest
        run: python versioning/main.py
        env:
          GITHUB_USERNAME: ${{ github.triggering_actor }}
          GITHUB_EMAIL: ${{ steps.test.outputs.emailGetter }}
          GITHUB_REF: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}

#  publish-release:
#    uses: PuzzlesHQ/Puzzles-Workflows/.github/workflows/maven-publishing.yml@main
#    secrets: inherit
#    with:
#      TAG_NAME: ${{ github.event.release.tag_name }}
#